force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobAppCloseStaleJobsBatchable.cls
public with sharing class JobAppCloseStaleJobsBatchable implements Database.Batchable<SObject> {

    // TODO: for unit testing, calculate a date 31 days ago from today
    //  and put into a JSON string that is a Job Application 
    //  then deserialize into a Job Application SObject
    //  insert the record

    public JobAppCloseStaleJobsBatchable() {}

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT 
                    Id,
                    Name,
                    Application_Status__c,
                    LastModifiedDate,
                    Notes__c
            FROM Job_Application__c
            WHERE Application_Status__c NOT IN ('Closed', 'Accepted') 
                AND LastModifiedDate <= N_DAYS_AGO:30
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Job_Application__c> scope) {
        for(Job_Application__c jobApp : scope) {
            jobApp.Application_Status__c = 'Closed';
            jobApp.Notes__c = 'This Application was closed by JobAppCloseStaleJobsBatchable.cls on ' + System.now().format();
        }
        List<Database.SaveResult> saveResults = Database.update(scope, false);
    }

    // TODO: maybe notify the user about the job when it's done
    public void finish(Database.BatchableContext bc) {}

}