force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanupStaleJobApplications.cls
public with sharing class CleanupStaleJobApplications {

    List<Job_Application__c> jobAppsToInsert = new List<Job_Application__c>();

    //pull all stale applications, close them, and update the note to reflect the change
    public void after30DaysWithoutInteraction() {
        for (Job_Application__c jobApp : [
                                            SELECT 
                                                Id, Name, Application_Status__c, LastModifiedDate, Notes__c

                                            FROM 
                                                Job_Application__c
                                            WHERE 
                                                Application_Status__c NOT IN ('Closed', 'Accepted') 
                                                AND LastModifiedDate <= N_DAYS_AGO:30
                                            ]
                                            ) {

            jobApp.Application_Status__c = 'Closed';
            jobApp.Notes__c = 'This Application was closed by CleanupStaleJobApplications.cls on' + System.now();
            jobAppsToInsert.add(jobApp);                                           
        }

        if(!jobAppsToInsert.isEmpty()) {
            Database.update(jobAppsToInsert);
        }
    
    }
}