force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Contact_Count__c.field-meta.xml
<CustomField>
    <fullName>Application_Contact_Count__c</fullName>
    <label>Application Contact Count</label>
    <summaryForeignKey>Job_Application_Contact__c.Job_Application__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that represents the main point of contact for the job. This could be a recruiter or employee at the company.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application_Contact__c/Job_Application_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Application Contact</label>
    <nameField>
        <label>Job Application Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Application Contacts</relationshipLabel>
    <relationshipName>Job_Application_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Application Contacts</relationshipLabel>
    <relationshipName>Job_Application_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PrimaryContactForJobApplicationBatchable.cls
/**
 * This class implements the Database.Batchable interface to process Job Application records
 * and assign a Primary Contact to those that currently do not have one.
 * 
 * The batch job performs the following steps:
 * 1. Queries all Job Application records where the Primary Contact is null.
 * 2. For each Job Application, assigns the first available Contact from the related Job Application Contacts.
 * 3. Updates the Job Application records in the database.
 */
public with sharing class PrimaryContactForJobApplicationBatchable implements Database.Batchable<sObject>{
    //Query for all Bob Applications without primary contact and return the query locator
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT 
                                            Id, Primary_Contact__c,
                                                (SELECT Id, Contact__c
                                                FROM Job_Application_Contacts__r
                                                WHERE Contact__c != null
                                                LIMIT 1)
                                        FROM 
                                            Job_Application__c 
                                        WHERE 
                                            Primary_Contact__c = null
                                            AND Application_Contact_Count__c > 0]);
    }

    /**
     * Executes the batch process for a given scope of Job_Application__c records.
     *
     * This method iterates through the provided scope of Job_Application__c records and sets the 
     * Primary_Contact__c field for each record. If the Job_Application_Contacts__r relationship 
     * is not empty, the Primary_Contact__c field is set to the Contact__c value of the first 
     * related Job_Application_Contact__c record.
     */
    public void execute(Database.BatchableContext bc, List<Job_Application__c> scope){
        for(Job_Application__c jobApp : scope) {
            //jobApp.Primary_Contact__c = jobApp.Job_Application_Contact__rs.isEmpty() ? null : jobApp.Job_Application_Contacts__r[0].Contact__c;
            if (!jobApp.Job_Application_Contacts__r.isEmpty()){
                jobApp.Primary_Contact__c = jobApp.Job_Application_Contacts__r[0].Contact__c;
                //System.debug('jobApp.Primary_Contact__c: ' + jobApp.Primary_Contact__c);
            }
        }

        Database.update(scope, false);    
    }

    public void finish(Database.BatchableContext bc){

    }
}

//weirdsourcer