force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JoobleJobSchedulerTest.cls
@IsTest
private class JoobleJobSchedulerTest {
    
    @IsTest
    static void testSchedulerRuns() {

        Test.startTest();

        //Use the mock
        Test.setMock(HttpCalloutMock.class, new JoobleJobMock()); 

        
        //Run the scheduler
        JoobleJobScheduler scheduler = new JoobleJobScheduler();
        scheduler.execute(null);
        
        Test.stopTest();

        //Verify jobs got inserted
        List<Job_Application__c> apps = [SELECT Id, Name, Application_Status__c FROM Job_Application__c];
        System.assertEquals(2, apps.size(), 'Two jobs should have been inserted from the mock response');
        System.assertEquals('Saved', apps[0].Application_Status__c, 'Status schould be Saved'); 
        
        //Simple assertion that test completed
        //System.assert(true, 'Scheduler executed without error.');
    }
}