force-app/main/default/objects/Interview_Contact__c/Interview_Contact__c.object-meta.xml
<CustomObject>
    <label>Interview Contact</label>
    <nameField>
        <label>Interview Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interview Contacts</relationshipLabel>
    <relationshipName>Interview_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interview_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <description>Job Application the interview is for</description>
    <formula>Interview__r.Name__r.Id</formula>
    <inlineHelpText>Job Application the interview is for</inlineHelpText>
    <label>Job Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Contact__c/Job_Application_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Application Contact</label>
    <nameField>
        <label>Job Application Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Application Contacts</relationshipLabel>
    <relationshipName>Job_Application_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Application Contacts</relationshipLabel>
    <relationshipName>Job_Application_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InterviewContToApplicationConHelper.cls
public with sharing class InterviewContToApplicationConHelper {

    //member variables to store list of Interview_Contact__c
    private List<Interview_Contact__c> interviewContactListToProcess;
    private String operationType;


    //constructor to process SObject records from Tigger to interviewContacts List
    public InterviewContToApplicationConHelper(List<SObject> interviewContacts, String operationTypeFromTrigger) {
        this.interviewContactListToProcess = (List<Interview_Contact__c>) interviewContacts;
        this.operationType = operationTypeFromTrigger;
    }

    public static void createApplicationContacts(List<Interview_Contact__c> interviewContactListToProcess) {
        Set<Id> jobApplicationIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();
        for (Interview_Contact__c interviewContact : interviewContactListToProcess) {
            //jobApplicationIds.add(interviewContact.Job_Application__c);
            contactIds.add(interviewContact.Contact__c);
        }
        //Check if there Application has a matching Application Contact
        List<Job_Application_Contact__c> jobApplicationContacts = [SELECT 
                                                                        Id, Contact__c, Job_Application__c 
                                                                    FROM 
                                                                        Job_Application_Contact__c 
                                                                    WHERE 
                                                                        //Job_Application__c IN :jobApplicationIds
                                                                        Contact__c IN :contactIds];

    }
}